name: demand
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.10.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

  # core:
  bloc: any
  dartz: any
  crypto: any
  flutter_bloc: any
  freezed: any
  freezed_annotation: any
  get_it: any
  provider: any

  # network:
  connectivity_plus: any
  dio: any
  shared_preferences: any

  # ui & components
  auto_size_text: ^3.0.0
  carousel_slider: ^5.1.1
  colornames: ^0.2.0
  easy_date_timeline:
    git:
      url: https://github.com/Muhammadyunusxon/easy_date_timeline.git
      ref: dev
  flutter_advanced_switch: ^3.1.0
  flutter_calendar_carousel: ^2.5.4
  flutter_html: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_rating_bar: ^4.0.1
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.3
  flutter_speed_dial: ^7.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.3
  flutter_swipe_detector: ^2.0.0
  ftoast: ^2.0.0
  google_fonts: ^7.0.0
  grouped_list: ^6.0.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  jiffy: ^6.4.4
  lottie: ^3.3.2
  phone_text_field: ^2.0.0
  proste_indexed_stack: ^0.2.4
  pull_to_refresh: ^2.0.0
  readmore: ^3.0.0
  rotated_corner_decoration: ^2.1.0+1
  shimmer: ^3.0.0
  sms_autofill: ^2.4.1
  smooth_page_indicator: ^2.0.1
  swipe_to: ^1.0.6
  zoom_pinch_overlay: ^1.4.3
  web_socket_channel: ^3.0.3
  flutter_libphonenumber: ^2.7.0

  # media:
  cached_network_image: ^3.4.1
  chewie: ^1.13.0
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  photo_view: ^0.15.0
  video_player: ^2.10.1

  # maps:
  geolocator: ^14.0.2
  google_maps_cluster_manager: ^3.1.0
  google_maps_flutter: ^2.14.0
  google_place:
    git:
      url: https://github.com/Muhammadyunusxon/google_place.git
  map_launcher: ^4.4.2
  osm_nominatim: ^4.0.1

  # firebase:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  
  # auth:
  app_tracking_transparency: ^2.0.6+1
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # services & utils
  add_2_calendar: ^3.0.1
  app_links: ^7.0.0
  collection: ^1.19.1
  device_info_plus: ^12.3.0
  flutter_displaymode: ^0.7.0
  flutter_downloader: ^1.12.0
  flutter_isolate: ^2.1.0
  path_provider: ^2.1.5
  payfast:
    git:
      url: https://github.com/Muhammadyunusxon/payfast_flutter.git
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_logo.png'
  adaptive_icon_foreground: 'assets/images/app_logo.png'
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  background_image: 'assets/images/splash.png'
  android_12:
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

